# This is a basic workflow to help you get started with Actions

name: MYSQL CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPER_SECRET: ${{ secrets.DB_PASSWORD }}
      DB_DATABASE: employees
      DB_USER: shashankthemoon

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start MySQL
        run: |
          mysql -u  $DB_USER -h 35.226.104.166 -P 3307  $DB_DATABASE --password=$SUPER_SECRET < query.sql
